### PR TITLE
Implement kicad_mod file output

### PR DESCRIPTION
**Pull request by kasbah**
This implements footprint output into a pcbart.kicad_mod file. Would be neat to have a way to automatically reload it into a kicad_pcb file too but that's for another day.

Would be nice to get feedback on all the three pull-request so far so I know I am not working on code that won't be merged.

### CODE REVIEW

**Comment by badgeek** [comment]
hi kaspar. i will merge this, im bit busy right now, wanted to test on windows too

**Comment by badgeek** [comment]
actually this is what i want in mind, thanks for making this! btw this friday hackchat hackaday.io will be talking about pcb art, im going to promote svg2shenzhen there

**Comment by kasbah** [comment]
So you have or will test on Windows before releasing? 

I saw that too about the hack chat, I let Andrew (who is the main guest of the chat) know about svg2shenzhen before that: https://twitter.com/kaspar_e/status/985409345625247744

**Comment by badgeek** [comment]
just tested this on windows and not working, there is a bug in windows when we try to create temp file, i fixed it before, i'll try to get this fixed

**Comment by badgeek** [comment]
@kasbah new release is out, removed mkstemp stuff because it is buggy on windows and use own cache folder cheers

**Pull request merged**
